In [1]:
import numpy as np

In [2]:
q1 = np.array([
    [200,220,250],
    [150,180,210],
	[300,330,360]
])

q2 = np.array([
	[209,231,259],
	[155,192,222],
	[310,340,375]
])

In [4]:
q1 + q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [7]:
q2 - q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [9]:
(q2-q1)*100/q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [13]:
prices = np.array([
	[10,12,11],
	[8,9,10],
	[15,16,17]
])

q1_revenue = q1 * prices
q1_revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [14]:
q1_discount = q1_revenue*0.3
q1_discount

array([[ 600.,  792.,  825.],
       [ 360.,  486.,  630.],
       [1350., 1584., 1836.]])

In [15]:
net_worth = q1_revenue - q1_discount
net_worth

array([[1400., 1848., 1925.],
       [ 840., 1134., 1470.],
       [3150., 3696., 4284.]])

In [16]:
np.sum(q1_discount)

np.float64(8463.0)

In [20]:
features = np.array([
	[2000,3],
	[1800,2]
])

weight = np.array([150,30000])

np.dot(features,weight)

array([390000, 330000])

In [23]:
b = np.array([1,2,3])
c = np.array([5,8,12])
np.cross(b,c)

array([ 0,  3, -2])

In [24]:
b = np.array([
	[1,2,3],
	[4,5,6],
	[7,8,9]
])

In [25]:
b[2,0]

np.int64(7)

In [30]:
b[:,0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])